# Future-climate consensus figure for Stenochrus portoricensis
# Requires objects/paths generated by the future-climate workflow.
library(terra)
library(sf)
library(ggplot2)
library(patchwork)

raster_to_df <- function(r) {
  d <- as.data.frame(r, xy = TRUE, na.rm = TRUE)
  names(d)[3] <- "value"
  d
}

plot_nac <- function(raster_file, panel_letter, panel_title, deptos_sf, col_sf, occ_colombia) {
  r <- terra::rast(raster_file)
  df <- raster_to_df(r)
  df$value <- factor(df$value, levels = 0:4)
  ggplot() +
    geom_raster(data=df, aes(x=x, y=y, fill=value)) +
    geom_sf(data=deptos_sf, fill=NA, colour="grey65", linewidth=0.18) +
    geom_sf(data=col_sf, fill=NA, colour="black", linewidth=0.50) +
    geom_point(data=occ_colombia, aes(decimalLongitude, decimalLatitude),
               shape=21, size=1.4, stroke=0.35, fill="white", colour="black") +
    scale_fill_manual(values=c("0"="#FFF7BC","1"="#FEC44F","2"="#FE9929","3"="#EC7014","4"="#CC4C02"),
                      limits=as.character(0:4),
                      name="NAC agreement\n(number of GCMs)",
                      drop=FALSE, na.translate=FALSE) +
    coord_sf(xlim=c(-79.2,-66.7), ylim=c(-4.4,13.0), expand=FALSE, datum=NA) +
    labs(title=panel_title, tag=panel_letter) +
    theme_void() +
    theme(plot.title=element_text(face="bold",hjust=.5,size=9),
          plot.tag=element_text(face="bold",size=13),
          plot.tag.position=c(.02,.98),
          legend.title=element_text(size=8,face="bold"),
          legend.text=element_text(size=7))
}

plot_suitability <- function(raster_file, panel_letter, panel_title, deptos_sf, col_sf, occ_colombia) {
  r <- terra::rast(raster_file)
  df <- raster_to_df(r)
  df$consensus <- ifelse(df$value < 2, "0–1", as.character(df$value))
  df$consensus <- factor(df$consensus, levels=c("0–1","2","3","4"))
  ggplot() +
    geom_raster(data=df, aes(x=x, y=y, fill=consensus)) +
    geom_sf(data=deptos_sf, fill=NA, colour="grey65", linewidth=0.18) +
    geom_sf(data=col_sf, fill=NA, colour="black", linewidth=0.50) +
    geom_point(data=occ_colombia, aes(decimalLongitude, decimalLatitude),
               shape=21, size=1.4, stroke=0.35, fill="white", colour="black") +
    scale_fill_manual(values=c("0–1"="#F2F2F2","2"="#A1DAB4","3"="#41B6C4","4"="#225EA8"),
                      limits=c("0–1","2","3","4"),
                      labels=c("0–1 GCM = no consensus","2/4 GCM suitable","3/4 GCM suitable","4/4 GCM suitable"),
                      name="Suitability\nagreement",
                      drop=FALSE, na.translate=FALSE) +
    coord_sf(xlim=c(-79.2,-66.7), ylim=c(-4.4,13.0), expand=FALSE, datum=NA) +
    labs(title=panel_title, tag=panel_letter) +
    theme_void() +
    theme(plot.title=element_text(face="bold",hjust=.5,size=9),
          plot.tag=element_text(face="bold",size=13),
          plot.tag.position=c(.02,.98),
          legend.title=element_text(size=8,face="bold"),
          legend.text=element_text(size=7))
}

# Example file names:
# NAC_agreement_SSP126_2041-2060.tif
# NAC_agreement_SSP585_2041-2060.tif
# NAC_agreement_SSP126_2061-2080.tif
# NAC_agreement_SSP585_2061-2080.tif
# GCM_agreement_SSP126_2041-2060.tif etc.
#
# Build A-D with plot_nac(), E-H with plot_suitability(), then:
# top_row <- (A+B+C+D) + plot_layout(ncol=4, guides="collect") & theme(legend.position="right")
# bottom_row <- (E+F+G+H) + plot_layout(ncol=4, guides="collect") & theme(legend.position="right")
# final_figure <- top_row / bottom_row
# ggsave("figures/future/Figure_future_NAC_suitability_consensus.png",
#        final_figure, width=15, height=10, units="in", dpi=300, bg="white")
